spring:
  profiles:
    active:
      - prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ENC(1umlUO1LVlWOK57oUFj5MX5y/0bkPctlrcEtRT7ReRmLKMCbHnsruAW1NK61gJArtO9kD/SUEpNBPXQlcW02Wg==)
    password: ENC(TBvK1FQb5UksjDNZ28MBnAk/kZLswnIPXctjmHMgqsTBAiM0QpGBkv4s1nbJ+WVIr3zyDssToUgJ/3mhnrl4pg==)
    url: jdbc:postgresql://localhost:5555/noticeboard_database
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistance:
          validation:
            mode: none
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
  mail:
    host: smtp.gmail.com
    username: ENC(bfL4vVL0JNWFmM2kyDxv3I75sApd/PEWmNerZM9oY4fm07vOCP7O9Gm6rRYTJnW5)
    password: ENC(EIBqM8XUC8dqi8NglfUDGSiC/TUZYl15y/kVlfvjF72nakgW9EXAGsAzBre1jcBmp3aOk0+li+TRzWQLIx5nIn7efrazqvqaK/OBkmRZICg=)
    properties:
      mail:
      smtp:
      auth: true
      port: 587
      starttls:
      enable: true
      transport:
      protocol: smtp
lock-user-account-on-start: true
upload-folder-path: static-uploads-dev
verify-address-email-url: https://localhost:3000/#/verify
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/noticeboard_database
    username: ENC(u3edAbI/m+ml48Hcb40SUemMd1lLdSLP1WJZEEoyFJ233I5lufv5e5HMtaY00LoCjYCX8vOH8Yq/rwfC5qvJCg==)
    password: ENC(m9ICFJjF2Cp64jn2C09RAFHPjGq/oXFiVPE3DqTs7GycRAokfNDrx+pXpqLuYB5PFWJ1YY4zwVfkf9jMKu2F2J6+M/A9nT/Vnnd9Ge4Pi2Y=)
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistance:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
  mail:
    host: smtp.gmail.com
    username: ENC(bfL4vVL0JNWFmM2kyDxv3I75sApd/PEWmNerZM9oY4fm07vOCP7O9Gm6rRYTJnW5)
    password: ENC(EIBqM8XUC8dqi8NglfUDGSiC/TUZYl15y/kVlfvjF72nakgW9EXAGsAzBre1jcBmp3aOk0+li+TRzWQLIx5nIn7efrazqvqaK/OBkmRZICg=)
    properties:
      mail:
      smtp:
      auth: true
      port: 587
      starttls:
      enable: true
      transport:
      protocol: smtp
lock-user-account-on-start: true
upload-folder-path: static-uploads-prod
verify-address-email-url: https://noticeboard.pl/#/verify
server:
  port: 443
  ssl:
    key-password: ENC(iaxQTEKRoFSSfcpBi5WUe6YoSCQ/WH0J72gjEwnWeQi5nn7WzZMjhhM/RgvduNBh)
    key-store-password: ENC(7/r+96rUerUSfSVkv1Wh3OWDwWuLuWbwJgs1jNk1hoENJMtxtDpYMdDU/bzZplzK)
    key-store: classpath:keystore.jks
    key-store-type: PKCS12
    key-alias: noticeboard
    key-store-provider: SUN
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      javax:
        persistance:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
  mail:
    default-encoding: UTF-8
    host: localhost
    username: username
    password: secret
    port: 2525
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: true
          starttls: true
    protocol: smtp
    test-connection: false
lock-user-account-on-start: false
upload-folder-path: static-uploads-test
verify-address-email-url: http://localhost:3000/verify
