spring:
  profiles:
    active:
    - dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Cj1dNIdO4JjRoNXe46yzF7dyokDJ
    url: jdbc:postgresql://localhost:5555/noticeboard_database
    username: noticeboard_user
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistance:
          validation:
            mode: none
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
  mail:
    host: smtp.gmail.com
    password: Lbep$gYDLR3*#o
    properties:
      mail:
        smtp:
          auth: true
          port: 587
          starttls:
            enable: true
        transport:
          protocol: smtp
    username: noticeboard.pl
upload-folder-path: static-uploads-dev
verify-address-email-url: http://localhost:3000/verify
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Cj1dNIdO4JjRoNXe46yzF7dyokDJ
    url: jdbc:postgresql://localhost:5555/noticeboard_database
    username: noticeboard_user
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistance:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
  mail:
    host: smtp.gmail.com
    password: Lbep$gYDLR3*#o
    properties:
      mail:
        smtp:
          auth: true
          port: 587
          starttls:
            enable: true
        transport:
          protocol: smtp
    username: noticeboard.pl
upload-folder-path: static-uploads-prod
verify-address-email-url: http://localhost:3000/verify
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      javax:
        persistance:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 12
        max-page-size: 36
upload-folder-path: static-uploads-test
verify-address-email-url: http://localhost:3000/verify
